DROP TABLE IF EXISTS
    app_user;

CREATE TABLE IF NOT EXISTS app_user (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
  , first_name TEXT NOT NULL
  , last_name TEXT NOT NULL
  , age INTEGER NOT NULL
  , country TEXT NOT NULL
  , city TEXT NOT NULL
  , email TEXT NOT NULL
);

DROP TABLE IF EXISTS
    app_thread;

CREATE TABLE IF NOT EXISTS app_thread (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
  , title TEXT NOT NULL
  , creator_id INTEGER NOT NULL
  , FOREIGN KEY (creator_id) REFERENCES app_user(id) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS
    app_comment;

CREATE TABLE IF NOT EXISTS app_comment (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
  , body TEXT NOT NULL
  , created TEXT NOT NULL
  , thread_id INTEGER NOT NULL
  , user_id INTEGER NOT NULL
  , FOREIGN KEY (thread_id) REFERENCES app_thread(id) ON DELETE CASCADE ON UPDATE CASCADE
  , FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS
    app_group;

CREATE TABLE IF NOT EXISTS app_group (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
  , name TEXT NOT NULL
);

DROP TABLE IF EXISTS
    app_group_user;

CREATE TABLE IF NOT EXISTS app_group_user (
    id INTEGER NOT NULL
  , group_id INTEGER NOT NULL
  , user_id INTEGER NOT NULL
  , PRIMARY KEY (id AUTOINCREMENT)
  , FOREIGN KEY (group_id) REFERENCES app_group(id) ON DELETE CASCADE ON UPDATE CASCADE
  , FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE ON UPDATE CASCADE
);
